[client.pv.activation]
proximity = "Proximity"

[server.pv.command.list]
empty = "no players with Plasmo Voice installed"
message = "Clients (%1$s/%2$s): %3$s"

[server.pv.command.mute]
already_muted = "%s already muted"
permanently_muted = "%1$s is permanently muted. Reason: %2$s"
temporarily_muted = "Muted %1$s %2$s. Reason: %3$s"
usage = "Usage: /vmute <player> [duration] [reason]"

[server.pv.command.mute_list]
empty = "No players are muted"
entry = "%1$s, expires: %2$s. Reason: %3$s"
entry_muted_by = "%1$s muted by %2$s, expires: %3$s. Reason: %4$s"
expiration_date = "yyyy.MM.dd"
expiration_time = "HH:mm:ss"
expire_at = "%1$s at %2$s"
header = "Muted players:"
never_expires = "never"

[server.pv.command.reconnect]
message = "Reconnect packet sent"

[server.pv.command.reload]
message = "Config reloaded"

[server.pv.command.unmute]
not_muted = "%s not muted"
unmuted = "Unmuted %s"
usage = "Usage: /vunmute <player>"

[server.pv.error]
mod_missing_kick_message = """
Sorry, you need to install the Plasmo Voice mod to play on this server.
Download here: https://modrinth.com/plugin/plasmo-voice"""
no_permissions = "&cI'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."
player_not_found = "Player not found"
player_only_command = "Only player can execute this command"
version_not_supported = "Sorry, your Plasmo Voice version is not supported on this server. %s"
version_not_supported_click = "Download supported version"
version_not_supported_hover = "%s"

[server.pv.mutes]
empty_reason = "not specified"
permanently_muted = "You've been permanently muted. Reason: %s"
temporarily_muted = "You've been muted %1$s. Reason: %2$s"
unmuted = "You've been unmuted"

[server.pv.mutes.durations]
days = "for %s d"
hours = "for %s h"
minutes = "for %s min"
seconds = "for %s sec"
weeks = "for %s w"
