[client.pv.activation]
broadcast = "Anúncio"

[server.pv.addon.broadcast]
broadcasting_specific = "Transmitir para %s"
broadcasting_wide = "Transmitir para %s"

[server.pv.addon.broadcast.command]
proxy_set = "Definir transmissão com modo de proxy"
server_set = "Definir transmissão com o modo de servidor para %s"
server_usage = "Uso: /vbroadcastproxy server <server names>"
usage = "Uso: /vbroadcastproxy <server|proxy> <server names>"
