[client.pv.activation]
discs = "Discos"

[server.pv.addon.discs.actionbar]
loading = "Cargando..."
playing = "Reproduciendo: %s"
track_not_found = "Pista no encontrada: %s"

[server.pv.addon.discs.arg]
label = "[label]"
search = "<search>"
url = "<url>"

[server.pv.addon.discs.error]
erase_wrong_item = "&cNo se puede borrar este objeto"
get_track_fail = "&cError al obtener la pista: %s"
no_permission = "&cNo tienes permisos"
not_a_record = "&cNecesitas tener un disco en tu mano para grabarlo"
search_fail = "&cError al obtener el resultado de la búsqueda: %s"
unknown_subcommand = "&cSubcomando desconocido. Comandos disponibles: %s"

[server.pv.addon.discs.format]
search_entry = "&e%1$s &7por %2$s"

[server.pv.addon.discs.success]
burn = "&aDisco grabado. Etiqueta: %s"
erase = "&aAudio personalizado eliminado"

[server.pv.addon.discs.usage]
burn = "&cUso: /discs burn <url> [label]"
