[client.pv.activation]
groups = "Grupos"

[server.pv.addon.groups]
divider = "&8&m-----------------------------------------------------"

[server.pv.addon.groups.arg]
groups_uuid = "<grupo uuid>"
name = "<nome>"
page = "[page]"
password = "<senha>"
permissions = "<lista de permissões>"

[server.pv.addon.groups.button]
invite = "&e✉ Convite"
join = "&e→ Entrar"
leave = "&c← Sair"
next = "&e>"
prev = "&e<"

[server.pv.addon.groups.command.browse.error]
no_groups = '&cNenhum grupo. Crie grupos usando "/groups create"'
page_not_found = "&cPágina não encontrada"

[server.pv.addon.groups.command.create]
success = "&aO grupo foi criado:"

[server.pv.addon.groups.command.invite]
success = "&aConvite enviado para %s"

[server.pv.addon.groups.command.invite.error]
already_joined = "&cJogador já entrou no grupo"
invite_self = "&cVocê não pode convidar a si mesmo"
usage = "&cUso: /groups invite <player>"

[server.pv.addon.groups.command.join]
success = "&aVocê entrou no grupo"

[server.pv.addon.groups.command.join.error]
already_joined = "&cVocê já entrou neste grupo"
usage = "&cUso: /groups join <group uuid> [password]"

[server.pv.addon.groups.command.leave]
success = "&aVocê saiu do grupo"

[server.pv.addon.groups.command.set.error]
identical_value = "&cO valor é idêntico ao valor atual"
unknown_flag = '&cPropriedade desconhecida: "%1$s". Propriedades disponíveis: %2$s'
usage = "&cUso: /groups set <flag> <value>"

[server.pv.addon.groups.command.transfer.error]
already_owner = "&cVocê já é o dono do grupo"
usage = "&cUso: /groups transfer <player>"

[server.pv.addon.groups.command.unset.error]
password_not_set = "&cGrupo já não está protegido com senha"
permissions_not_set = "&cO filtro de permissões já está vazio"
unknown_flag = '&cNão é possível remover a propriedade "%1$s". Propriedades disponíveis: %2$s'
usage = "&cUso: /groups unset <flag>"

[server.pv.addon.groups.error]
group_not_found = "&cGrupo não encontrado"
name_length = "&cNome do grupo deve conter entre %1$s e %2$s caracteres"
no_permission = "&cSem permissão: '%s'"
not_in_group = "&cVocê precisa estar no grupo para executar este comando"
player_not_found = "&cNenhum jogador com esse nome"
unknown = "&cErro desconhecido"
unknown_subcommand = "&cComando desconhecido. Comandos disponíveis: %s"
uuid_parse = "Erro de análise &cUuid. '%s' não é um Uuid"

[server.pv.addon.groups.format]
group_name = "&6[%s]"
invite = "%1$s convidou você para participar do grupo de voz %2$s"
only_players = "&7Jogadores: &r%s"
page = "&7Página &r%s/%s"
players_and_owner = "&7Jogadores: &r%1$s&7, propriedade de &r%2$s"

[server.pv.addon.groups.icons]
password_protected = "&6⛨"

[server.pv.addon.groups.notifications]
group_deleted = "O grupo foi excluído"
kicked = "&cVocê foi expulso do grupo"
name_change = "Nome do grupo foi alterado de '%1$s' para '%2$s'"
new_owner = "%s é o novo dono do grupo"
password_changed = "Senha do grupo alterada"
password_unset = "Proteção por senha foi removida"
permissions_changed = "Permissões do grupo alteradas"
permissions_unset = "A proteção de permissões foi removida"
persistent_false = "O grupo não é mais persistente"
persistent_true = "O grupo é persistente agora"
player_join = "%s juntou-se ao grupo"
player_kicked = "%s foi expulso do grupo"
player_left = "%s saiu do grupo"

[server.pv.addon.groups.tooltip]
group_uuid = "Uuid: %s"
password_protected = "O grupo é protegido por senha"
