[client.pv.activation]
broadcast = "Broadcast"

[server.pv.addon.broadcast]
broadcasting_specific = "Broadcasting to %s"
broadcasting_wide = "Broadcasting to %s-wide"

[server.pv.addon.broadcast.command]
range_set = "Set broadcast with range %d"
range_usage = "Usage: /vbroadcast range <number greater than 0>"
server_set = "Set broadcast with mode server"
usage = "Usage: /vbroadcast <range|server|world> <range|world names>"
world_set = "Set broadcast with mode world to %s"
world_usage = "Usage: /vbroadcast world <world names>"
