name: Crowdin Addons

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  crowdin-download:
    runs-on: ubuntu-latest
    container:
      image: crowdin/cli:4.1.2
      env:
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: addons
      - name: Download crowdin bundles
        run: |
          crowdin bundle download 8
          crowdin bundle download 10
          find . -type f -empty -print -delete
          find . -type d -empty -print -delete
      - name: Push crowdin changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Crowdin download"
          git push
